using System;
using UnityEngine;

public enum SuitRole : byte { Keep, Primary, Secondary, Trim }

/// Suit recolour data for one Sidekick character (generated by Overpowered > Forge > Sidekick heroes, editable after).
/// Sidekick colours come from a 32x32 point-filtered colour map of 2x2 swatches indexed by part UVs. The suit keeps a
/// readable copy of the character's authored map and the role of every swatch its mesh uses: skin/hair/eyes and special
/// materials stay as authored (Keep); outfit swatches take the loadout's Primary/Secondary palette colours, dark trims the
/// Trim palette colour. Recolour is self-contained: no Sidekick runtime API, database or SQLite at runtime.
[CreateAssetMenu(menuName="Overpowered/Forge/Sidekick Suit")]
public sealed class SidekickSuit : ScriptableObject
{
    [Serializable] public struct Swatch { public Vector2Int Cell; public SuitRole Role; public string Name; public int Vertices; }
    [Tooltip("The Sidekick character prefab this suit belongs to.")] public GameObject Prefab;
    [Tooltip("The Sidekick material on the character prefab; only renderer slots using it are recoloured.")] public Material Source;
    [Tooltip("Readable RGBA32 copy of Source's authored _ColorMap.")] public Texture2D BaseColorMap;
    public CityColor Trim=CityColor.Metal;
    [Tooltip("Off (default): the suit colour map is drawn by the Standard shader like every palette material, plus the source's emission map. " +
        "On: a copy of the authored Sidekick_ShaderGraph material. Measured in the densest street: the ShaderGraph hero cost +1.9 ms/frame (STATUS).")]
    public bool AuthoredShader;
    public Swatch[] Swatches;
    public const string ColorMapProperty="_ColorMap";
    public const int CellPixels=2;
    /// A new point-filtered colour map with the given palette colours. Callers own and cache it (CityMaterials.Suit).
    public Texture2D Build(Color primary,Color secondary,Color trim)
    {
        var map=new Texture2D(BaseColorMap.width,BaseColorMap.height,TextureFormat.RGBA32,false){name="Suit colour map "+name,filterMode=FilterMode.Point,wrapMode=TextureWrapMode.Clamp,anisoLevel=0};
        Write(map,primary,secondary,trim);return map;
    }
    public void Write(Texture2D map,Color primary,Color secondary,Color trim)
    {
        var pixels=BaseColorMap.GetPixels32();int width=BaseColorMap.width;
        foreach(var s in Swatches)
        {
            if(s.Role==SuitRole.Keep)continue;
            Color32 c=s.Role==SuitRole.Primary?primary:s.Role==SuitRole.Secondary?secondary:trim;c.a=255;
            for(int y=0;y<CellPixels;y++)for(int x=0;x<CellPixels;x++)pixels[(s.Cell.y*CellPixels+y)*width+s.Cell.x*CellPixels+x]=c;
        }
        map.SetPixels32(pixels);map.Apply(false,false);
    }
    public static Color32 Pixel(Texture2D map,Vector2Int cell)=>map.GetPixel(cell.x*CellPixels,cell.y*CellPixels);
    /// The colour map a suit material draws with, whichever shader it uses.
    public static Texture MapOf(Material material)=>material.HasProperty(ColorMapProperty)&&material.GetTexture(ColorMapProperty)!=null?material.GetTexture(ColorMapProperty):material.mainTexture;
    /// ONE material for (this suit, colours); CityMaterials owns and caches it.
    public Material CreateMaterial(Texture2D map,string materialName,float smoothness)
    {
        Material material;
        if(AuthoredShader){material=new Material(Source);material.SetTexture(ColorMapProperty,map);}
        else
        {
            material=new Material(Shader.Find("Standard")){enableInstancing=true,mainTexture=map};material.SetFloat("_Glossiness",smoothness);
            var emission=Source.HasProperty("_EmissionMap")?Source.GetTexture("_EmissionMap"):null;
            if(emission!=null){material.SetTexture("_EmissionMap",emission);material.SetColor("_EmissionColor",Color.white);material.EnableKeyword("_EMISSION");}
        }
        material.name=materialName;return material;
    }
}
